services:
  - type: web
    name: AskVerse_the_Chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: JWT_SECRET_KEY
        sync: false
        
      - key: GROQ_API_KEY
        sync: false
      
      - key: DATABASE_URL
        sync: false
      
      - key: DB_USER
        sync: false
      
      - key: DB_PASSWORD
        sync: false
      
      - key: DB_HOST
        sync: false
      
      - key: DB_PORT
        sync: false
      
      - key: DB_NAME
        sync: false