name: Keep Render App Awake

on:
  schedule:
    - cron: '*/15 2-16 * * *'  # Every 15 mins from 8:00 AM to 9:30 PM IST
  workflow_dispatch:

jobs:
  wake-render:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Render App
        run: |
          curl -s --request GET https://askverse-the-chatbot.onrender.com/docs > /dev/null
