name: Wake Render Service

on:
  schedule:
    # Every 15 minutes from 2:30 AM to 4:00 PM UTC (8:00 AM – 9:30 PM IST)
    - cron: '*/15 2-16 * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up AskVerse backend
        run: |
          echo "Sending wake-up ping to Render..."
          curl -s -o /dev/null -w "%{http_code}" https://askverse-the-chatbot-9wcc.onrender.com/docs || echo "Wake failed, but continuing"
